logLevel: info
logDestinations: [stdout]
logStructured: true

authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
        path:
      - action: read
        path:
      - action: playback
        path:
      - action: api

api: true
apiAddress: :9997

rtsp: true
rtspTransports: [tcp]
rtspAddress: :8554

rtmp: false
webrtc: false
srt: false

hls: true
hlsAddress: :8888
hlsAllowOrigins: ['*']
hlsVariant: lowLatency

pathDefaults:
  source: publisher

paths:
  all_others:
