bind 0.0.0.0
protected-mode no
port 6379

appendonly yes
appendfsync everysec
save 60 1000

tcp-keepalive 60
timeout 0
databases 16

# Redis Pub/Sub is enabled by default. Publish expire events for track TTLs only.
notify-keyspace-events Ex
